# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-01 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='name',
        ),
        migrations.AddField(
            model_name='birthday',
            name='realname',
            field=models.CharField(default='whatever', max_length=255),
            preserve_default=False,
        ),
    ]
